name: Issue Triage
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: contains(github.event.issue.title, 'bug')
        with:
          labels: bug
      - uses: actions-ecosystem/action-add-labels@v1
        if: contains(github.event.issue.title, 'docs')
        with:
          labels: documentation